apiVersion: v1
kind: Pod
metadata:
  name: argocd-lab
  labels:
    app.kubernetes.io/name: argocd-lab
spec:
  containers:
    - name: argotest
      image: localhost:32000/aravn/argotest:1.0.0
      ports:
        - containerPort: 3333
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-lab
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-lab
  ports:
    - port: 3333
      targetPort: 3333
      nodePort: 32001